import JSZip from "jszip";
import { saveAs } from "file-saver";

interface GeneratedFile {
  path: string;
  content: string;
}

export async function downloadProjectZip(projectName: string, files: GeneratedFile[]) {
  const zip = new JSZip();
  const safeName = (projectName || "zyntarix-app")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 30);

  // 1. Synthesized App Files
  if (files && files.length > 0) {
    files.forEach((f) => {
      zip.file(f.path, f.content);
    });
  } else {
    zip.file(
      "src/app/page.tsx",
      `export default function Home() {\n  return (\n    <main className="p-8">\n      <h1>${projectName}</h1>\n    </main>\n  );\n}`
    );
  }

  // 2. package.json
  const packageJson = {
    name: safeName,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies: {
      react: "^18.2.0",
      "react-dom": "^18.2.0",
      next: "14.1.0",
      "lucide-react": "^0.344.0",
      "tailwind-merge": "^2.2.1",
      clsx: "^2.1.0",
    },
    devDependencies: {
      typescript: "^5",
      "@types/node": "^20",
      "@types/react": "^18",
      "@types/react-dom": "^18",
      autoprefixer: "^10.0.1",
      postcss: "^8",
      tailwindcss: "^3.3.0",
    },
  };
  zip.file("package.json", JSON.stringify(packageJson, null, 2));

  // 3. tailwind.config.ts
  const tailwindConfig = `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;`;
  zip.file("tailwind.config.ts", tailwindConfig);

  // 4. postcss.config.js
  const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`;
  zip.file("postcss.config.js", postcssConfig);

  // 5. tsconfig.json
  const tsConfig = {
    compilerOptions: {
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: {
        "@/*": ["./src/*"],
      },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  };
  zip.file("tsconfig.json", JSON.stringify(tsConfig, null, 2));

  // 6. src/app/layout.tsx
  const layoutContent = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${projectName || "Zyntarix Synthesized App"}",
  description: "Generated by Zyntarix Autonomous Platform",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`;
  zip.file("src/app/layout.tsx", layoutContent);

  // 7. src/app/globals.css
  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  padding: 0;
}`;
  zip.file("src/app/globals.css", globalsCss);

  // 8. README.md
  const readmeContent = `# ${projectName}

Synthesized by **Zyntarix Autonomous Platform**.

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run local development server:
\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.`;
  zip.file("README.md", readmeContent);

  // 9. Generate & Trigger Download
  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `${safeName}.zip`);
}

